const population = [
	{
		id: 1,
		personName: 'Alice Johnson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 0, 15, 8, 30),
		rating: 5,
		commentary: 'Absolutely fantastic experience! Highly recommend.',
		topic: 'ADVENTURE',
	},
	{
		id: 2,
		personName: 'Bob Smith',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 1, 22, 14, 45),
		rating: 3,
		commentary: 'It was okay, but I expected more based on the reviews.',
		topic: 'ADVENTURE',
	},
	{
		id: 3,
		personName: 'Carol White',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 2, 5, 11, 20),
		rating: 4,
		commentary: 'Good content, but some areas could be improved.',
		topic: 'ADVENTURE',
	},
	{
		id: 4,
		personName: 'David Brown',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 3, 10, 9, 15),
		rating: 2,
		commentary: 'Not great. Had higher expectations.',
		topic: 'ADVENTURE',
	},
	{
		id: 5,
		personName: 'Eva Green',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 4, 22, 17, 30),
		rating: 5,
		commentary: 'Exceptional work! Would definitely visit again.',
		topic: 'ADVENTURE',
	},
	{
		id: 6,
		personName: 'Frank Harris',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 5, 6, 13, 50),
		rating: 1,
		commentary: 'Very disappointing. Would not recommend.',
		topic: 'ADVENTURE',
	},
	{
		id: 7,
		personName: 'Grace Adams',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 6, 21, 15, 0),
		rating: 4,
		commentary: 'Great content with some minor issues.',
		topic: 'ADVENTURE',
	},
	{
		id: 8,
		personName: 'Henry Clark',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 7, 12, 10, 25),
		rating: 3,
		commentary: 'Average experience, not bad but not great either.',
		topic: 'ADVENTURE',
	},
	{
		id: 9,
		personName: 'Ivy Lewis',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 8, 18, 12, 30),
		rating: 5,
		commentary: 'Amazing insights and well-written articles!',
		topic: 'ADVENTURE',
	},
	{
		id: 10,
		personName: 'Jack Walker',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 9, 25, 14, 40),
		rating: 2,
		commentary: 'Not up to the mark, could use some improvements.',
		topic: 'ADVENTURE',
	},
	{
		id: 11,
		personName: 'Kara Scott',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 10, 9, 16, 20),
		rating: 4,
		commentary: 'Good read with useful information.',
		topic: 'ADVENTURE',
	},
	{
		id: 12,
		personName: 'Liam King',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 11, 1, 11, 10),
		rating: 3,
		commentary: 'Interesting but lacked depth in some areas.',
		topic: 'ADVENTURE',
	},
	{
		id: 13,
		personName: 'Mona Patel',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 0, 28, 9, 55),
		rating: 5,
		commentary: 'Fantastic! Exceeded all my expectations.',
		topic: 'ADVENTURE',
	},
	{
		id: 14,
		personName: 'Nate Allen',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 1, 17, 12, 40),
		rating: 1,
		commentary: 'Very poor quality, wouldn’t recommend.',
		topic: 'ADVENTURE',
	},
	{
		id: 15,
		personName: 'Olivia Carter',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 2, 23, 14, 10),
		rating: 4,
		commentary: 'Well-written and informative, worth reading.',
		topic: 'ADVENTURE',
	},
	{
		id: 16,
		personName: 'Paul Harris',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 3, 30, 18, 25),
		rating: 2,
		commentary: 'Had high hopes but was let down.',
		topic: 'ADVENTURE',
	},
	{
		id: 17,
		personName: 'Quinn Young',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 4, 15, 10, 35),
		rating: 5,
		commentary: 'Top-notch content, very engaging and helpful.',
		topic: 'ADVENTURE',
	},
	{
		id: 18,
		personName: 'Riley Johnson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 5, 4, 12, 0),
		rating: 3,
		commentary: 'Decent but could use more detail.',
		topic: 'ADVENTURE',
	},
	{
		id: 19,
		personName: 'Samantha Lee',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 6, 12, 16, 10),
		rating: 4,
		commentary: 'Good insights, though some parts felt rushed.',
		topic: 'ADVENTURE',
	},
	{
		id: 20,
		personName: 'Tom Wilson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 7, 20, 14, 55),
		rating: 2,
		commentary: 'Not worth the time, lacks valuable content.',
		topic: 'ADVENTURE',
	},
	{
		id: 21,
		personName: 'Ursula Martin',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 0, 7, 8, 0),
		rating: 5,
		commentary: 'Breathtaking views and detailed observations.',
		topic: 'NATURE',
	},
	{
		id: 22,
		personName: 'Victor Martinez',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 1, 14, 11, 30),
		rating: 4,
		commentary: 'Very informative, though a bit lengthy.',
		topic: 'NATURE',
	},
	{
		id: 23,
		personName: 'Wendy Clark',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 2, 12, 9, 20),
		rating: 3,
		commentary: 'Nice content but could use more visuals.',
		topic: 'NATURE',
	},
	{
		id: 24,
		personName: 'Xander Lee',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 3, 16, 14, 40),
		rating: 2,
		commentary: 'Disappointing, didn’t meet expectations.',
		topic: 'NATURE',
	},
	{
		id: 25,
		personName: 'Yara Thompson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 4, 10, 12, 15),
		rating: 5,
		commentary: 'Exceptional detail and stunning photographs.',
		topic: 'NATURE',
	},
	{
		id: 26,
		personName: 'Zachary Evans',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 5, 8, 13, 25),
		rating: 4,
		commentary: 'Great insights, though a bit repetitive.',
		topic: 'NATURE',
	},
	{
		id: 27,
		personName: 'Amelia Davis',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 6, 5, 10, 10),
		rating: 3,
		commentary: 'Interesting but lacks depth.',
		topic: 'NATURE',
	},
	{
		id: 28,
		personName: 'Benjamin Lewis',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 7, 20, 15, 0),
		rating: 4,
		commentary: 'Well-written and engaging.',
		topic: 'NATURE',
	},
	{
		id: 29,
		personName: 'Catherine Harris',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 8, 15, 11, 45),
		rating: 5,
		commentary: 'Fantastic read with detailed information.',
		topic: 'NATURE',
	},
	{
		id: 30,
		personName: 'Daniel Walker',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 9, 25, 13, 35),
		rating: 2,
		commentary: 'Not very engaging or insightful.',
		topic: 'NATURE',
	},
	{
		id: 31,
		personName: 'Ella Robinson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 10, 10, 9, 0),
		rating: 3,
		commentary: 'Good attempt but lacks visual appeal.',
		topic: 'NATURE',
	},
	{
		id: 32,
		personName: 'Felix Martinez',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 11, 20, 14, 30),
		rating: 4,
		commentary: 'Very informative, some minor issues.',
		topic: 'NATURE',
	},
	{
		id: 33,
		personName: 'Grace Wilson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 0, 23, 16, 0),
		rating: 5,
		commentary: 'Incredible details and fascinating observations.',
		topic: 'NATURE',
	},
	{
		id: 34,
		personName: 'Henry Lewis',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 1, 18, 11, 15),
		rating: 2,
		commentary: 'Fell short of expectations.',
		topic: 'NATURE',
	},
	{
		id: 35,
		personName: 'Isabella Davis',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 2, 28, 12, 25),
		rating: 4,
		commentary: 'Good content with minor flaws.',
		topic: 'NATURE',
	},
	{
		id: 36,
		personName: 'Jack Smith',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 3, 15, 10, 45),
		rating: 3,
		commentary: 'Decent but could use more engaging visuals.',
		topic: 'NATURE',
	},
	{
		id: 37,
		personName: 'Kara White',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 4, 8, 15, 30),
		rating: 5,
		commentary: 'Absolutely fantastic, couldn’t ask for more.',
		topic: 'NATURE',
	},
	{
		id: 38,
		personName: 'Liam Johnson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 5, 20, 13, 15),
		rating: 3,
		commentary: 'Interesting content but could use more depth.',
		topic: 'NATURE',
	},
	{
		id: 39,
		personName: 'Mia Green',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 6, 12, 14, 5),
		rating: 4,
		commentary: 'Great article with some minor issues.',
		topic: 'NATURE',
	},
	{
		id: 40,
		personName: 'Noah Martin',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 7, 25, 16, 20),
		rating: 2,
		commentary: 'Disappointing content, didn’t meet the hype.',
		topic: 'NATURE',
	},
	{
		id: 41,
		personName: 'Olivia King',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 0, 12, 10, 10),
		rating: 5,
		commentary: 'Absolutely stylish and trendy outfits showcased.',
		topic: 'FASHION',
	},
	{
		id: 42,
		personName: 'Paul Adams',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 1, 18, 12, 0),
		rating: 4,
		commentary: 'Great fashion tips and inspirations.',
		topic: 'FASHION',
	},
	{
		id: 43,
		personName: 'Quinn Harris',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 2, 25, 14, 30),
		rating: 3,
		commentary: 'Good content but lacks variety.',
		topic: 'FASHION',
	},
	{
		id: 44,
		personName: 'Rachel Moore',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 3, 10, 15, 45),
		rating: 2,
		commentary: 'Not very engaging or useful.',
		topic: 'FASHION',
	},
	{
		id: 45,
		personName: 'Samuel Carter',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 4, 20, 17, 0),
		rating: 5,
		commentary: 'Fantastic insights into the latest fashion trends.',
		topic: 'FASHION',
	},
	{
		id: 46,
		personName: 'Tina Scott',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 5, 30, 13, 30),
		rating: 4,
		commentary: 'Stylish and informative, a must-read.',
		topic: 'FASHION',
	},
	{
		id: 47,
		personName: 'Ulysses Green',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 6, 15, 11, 45),
		rating: 3,
		commentary: 'Nice content but could use more depth.',
		topic: 'FASHION',
	},
	{
		id: 48,
		personName: 'Victoria Wright',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 7, 22, 10, 10),
		rating: 4,
		commentary: 'Great style tips, though some ideas felt repetitive.',
		topic: 'FASHION',
	},
	{
		id: 49,
		personName: 'William Johnson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 8, 30, 12, 20),
		rating: 5,
		commentary: 'Impressive collection of fashion trends and tips.',
		topic: 'FASHION',
	},
	{
		id: 50,
		personName: 'Xena Lee',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 9, 18, 14, 35),
		rating: 3,
		commentary: 'Interesting content but a bit lacking in detail.',
		topic: 'FASHION',
	},
	{
		id: 51,
		personName: 'Yvonne Thompson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 10, 12, 16, 0),
		rating: 2,
		commentary: 'Didn’t find the content very inspiring.',
		topic: 'FASHION',
	},
	{
		id: 52,
		personName: 'Zane Brown',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 11, 4, 17, 30),
		rating: 4,
		commentary: 'Well-done, but some outfits were outdated.',
		topic: 'FASHION',
	},
	{
		id: 53,
		personName: 'Amy Green',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 0, 25, 13, 45),
		rating: 5,
		commentary: 'Amazing content with the latest fashion trends.',
		topic: 'FASHION',
	},
	{
		id: 54,
		personName: 'Brian Hall',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 1, 5, 14, 50),
		rating: 3,
		commentary: 'Decent fashion tips but could use more variety.',
		topic: 'FASHION',
	},
	{
		id: 55,
		personName: 'Chloe Scott',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 2, 17, 10, 30),
		rating: 2,
		commentary: 'Not very engaging or useful.',
		topic: 'FASHION',
	},
	{
		id: 56,
		personName: 'Derek Morris',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 3, 23, 11, 55),
		rating: 4,
		commentary: 'Good insights, though some sections felt rushed.',
		topic: 'FASHION',
	},
	{
		id: 57,
		personName: 'Emily Adams',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 4, 12, 12, 10),
		rating: 5,
		commentary: 'Fantastic fashion blog with great details and photos.',
		topic: 'FASHION',
	},
	{
		id: 58,
		personName: 'Frankie Wilson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 5, 19, 15, 20),
		rating: 3,
		commentary: 'Interesting but could use more examples.',
		topic: 'FASHION',
	},
	{
		id: 59,
		personName: 'Grace Martinez',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 6, 8, 13, 0),
		rating: 2,
		commentary: 'Lacks depth and creativity.',
		topic: 'FASHION',
	},
	{
		id: 60,
		personName: 'Hannah Lee',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 7, 30, 14, 50),
		rating: 5,
		commentary: 'Incredible fashion ideas and well-presented.',
		topic: 'FASHION',
	},
	{
		id: 61,
		personName: 'Isaac White',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 8, 12, 16, 30),
		rating: 4,
		commentary: 'Stylish and engaging content.',
		topic: 'FASHION',
	},
	{
		id: 62,
		personName: 'Julia King',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 9, 22, 10, 10),
		rating: 3,
		commentary: 'Good content but lacks variety in styles.',
		topic: 'FASHION',
	},
	{
		id: 63,
		personName: 'Kyle Rogers',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 10, 11, 15, 35),
		rating: 2,
		commentary: 'Not engaging and lacks depth.',
		topic: 'FASHION',
	},
	{
		id: 64,
		personName: 'Laura White',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 11, 18, 12, 25),
		rating: 4,
		commentary: 'Very stylish and well-written.',
		topic: 'FASHION',
	},
	{
		id: 65,
		personName: 'Matthew Carter',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 0, 10, 11, 50),
		rating: 5,
		commentary: 'Outstanding content with the latest trends.',
		topic: 'FASHION',
	},
	{
		id: 66,
		personName: 'Nina Morris',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 1, 14, 12, 30),
		rating: 3,
		commentary: 'Decent but could use more innovative ideas.',
		topic: 'FASHION',
	},
	{
		id: 67,
		personName: 'Oscar Nelson',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 2, 20, 14, 15),
		rating: 2,
		commentary: 'Not very engaging or helpful.',
		topic: 'FASHION',
	},
	{
		id: 68,
		personName: 'Paige Wright',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 3, 25, 16, 40),
		rating: 4,
		commentary: 'Good read with interesting fashion ideas.',
		topic: 'FASHION',
	},
	{
		id: 69,
		personName: 'Quincy Adams',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 4, 10, 12, 20),
		rating: 5,
		commentary: 'Fantastic fashion tips and insights.',
		topic: 'FASHION',
	},
	{
		id: 70,
		personName: 'Rita Scott',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 5, 15, 13, 30),
		rating: 3,
		commentary: 'Good content but could be more detailed.',
		topic: 'FASHION',
	},
	{
		id: 77,
		personName: 'Gary Parker',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 0, 8, 14, 0),
		rating: 5,
		commentary: 'Fantastic take on the latest modern trends!',
		topic: 'MODERN',
	},
	{
		id: 78,
		personName: 'Helen Ford',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 1, 12, 9, 30),
		rating: 4,
		commentary: 'Great insights into contemporary design.',
		topic: 'MODERN',
	},
	{
		id: 79,
		personName: 'Isaac Newton',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 2, 15, 11, 10),
		rating: 3,
		commentary: 'Somewhat informative but lacks depth.',
		topic: 'MODERN',
	},
	{
		id: 80,
		personName: 'Jessica Brown',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 3, 20, 16, 45),
		rating: 5,
		commentary: 'A must-read for anyone into modern art.',
		topic: 'MODERN',
	},
	{
		id: 81,
		personName: 'Kyle Edwards',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 4, 25, 14, 20),
		rating: 2,
		commentary: 'Didn’t live up to the expectations.',
		topic: 'MODERN',
	},
	{
		id: 82,
		personName: 'Linda Holmes',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 5, 2, 12, 15),
		rating: 4,
		commentary: 'Very engaging with relevant trends.',
		topic: 'MODERN',
	},
	{
		id: 83,
		personName: 'Michael Jenkins',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 6, 18, 10, 55),
		rating: 3,
		commentary: 'Could have been more thorough.',
		topic: 'MODERN',
	},
	{
		id: 84,
		personName: 'Natalie Garcia',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 7, 21, 9, 0),
		rating: 5,
		commentary: 'Exceptional piece on modern innovations.',
		topic: 'MODERN',
	},
	{
		id: 85,
		personName: 'Oliver Martin',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 8, 10, 14, 30),
		rating: 4,
		commentary: 'Good but felt repetitive at times.',
		topic: 'MODERN',
	},
	{
		id: 86,
		personName: 'Paula Wright',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 9, 5, 12, 40),
		rating: 2,
		commentary: 'Not what I expected, too generic.',
		topic: 'MODERN',
	},
	{
		id: 87,
		personName: 'Quentin Brooks',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 10, 13, 16, 0),
		rating: 5,
		commentary: 'Outstanding! Full of fresh modern ideas.',
		topic: 'MODERN',
	},
	{
		id: 88,
		personName: 'Rachel Adams',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 11, 1, 15, 45),
		rating: 3,
		commentary: 'Decent but lacks originality.',
		topic: 'MODERN',
	},
	{
		id: 89,
		personName: 'Steve Cooper',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 0, 27, 11, 20),
		rating: 4,
		commentary: 'Modern and unique content!',
		topic: 'MODERN',
	},
	{
		id: 90,
		personName: 'Tina White',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 1, 15, 9, 35),
		rating: 5,
		commentary: 'Top-notch article on modern designs.',
		topic: 'MODERN',
	},
	{
		id: 91,
		personName: 'Uma Patel',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 2, 11, 14, 55),
		rating: 4,
		commentary: 'Very detailed and well-researched.',
		topic: 'MODERN',
	},
	{
		id: 92,
		personName: 'Victor Harris',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 3, 20, 16, 50),
		rating: 2,
		commentary: 'Did not meet my expectations.',
		topic: 'MODERN',
	},
	{
		id: 93,
		personName: 'Wendy Lewis',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 4, 18, 12, 20),
		rating: 3,
		commentary: 'Informative but lacked new insights.',
		topic: 'MODERN',
	},
	{
		id: 94,
		personName: 'Xander Scott',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 5, 24, 15, 10),
		rating: 5,
		commentary: 'Incredibly engaging and thorough.',
		topic: 'MODERN',
	},
	{
		id: 95,
		personName: 'Yasmin Green',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 6, 2, 13, 35),
		rating: 4,
		commentary: 'Loved the fresh perspective!',
		topic: 'MODERN',
	},
	{
		id: 96,
		personName: 'Zane Hughes',
		avatar: '/src/assets/images/avatars/gojo.webp',
		pubData: new Date(2024, 7, 17, 10, 45),
		rating: 3,
		commentary: 'Good read, but needed more depth.',
		topic: 'MODERN',
	},
];

export default population;
